qnx/
0:0:0775:O_CREAT

qnx/qdb/
0:0:0775:O_CREAT

bipd/
0:0:0775:O_CREAT

bipd/files
0:0:0666:server,O_CREAT
user::rw
group::rw
other::rw
mask::rw


system/
0:0:0777:O_CREAT

system/info/
0:0:0666:O_CREAT
user::rw
group::rw
other::rw

system/navigator/
0:0:0777:O_CREAT

system/navigator/status/
0:0:0777:O_CREAT

system/navigator/status/mobile_hotspot
0:0:0777:O_CREAT

system/navigator/status/tethering
0:0:0777:O_CREAT


services/
0:0:0770:O_CREAT
user::rwx
group::rwx
other::
mask::rwx
group:31:rx
group:379:rx

services/geolocation/
0:0:0666:O_CREAT

services/geolocation/control
0:0:0666:server
user::rw
group::rw
other::rw
mask::rw

services/notify/
0:0:0775:O_CREAT

services/notify/settings/
0:0:0750:O_CREAT
user::rwx
group::rx
other::
mask::rx
group:379:rx
group:87:rx

services/notify/settings/global
0:0:0666:O_CREAT

services/tethering/
0:0:0770:O_CREAT
user::rwx
group::rwx
other::
mask::rwx
group:31:rx
group:379:rx

services/tethering/config
42:42:0600

services/tethering/control
42:0:0660:server,O_CREAT
user::rw
group::rw
other::
mask::rw
user:456:rw

services/wifi/
0:0:0770:O_CREAT
user::rwx
group::rwx
other::
mask::rwx
group:31:rx
group:379:rx

services/wifi/control
42:0:0660:server,O_CREAT
user::rw
group::rw
other::
mask::rw
user:456:rw

services/cellular/
0:0:0770:O_CREAT
user::rwx
group::rwx
other::
mask::rwx
group:31:rx
group:379:rx

services/cellular/uicc/
0:0:0770:O_CREAT
user::rwx
group::rwx
other::
mask::rwx
group:31:rx
group:379:rx

services/cellular/radioctrl/
0:0:0770:O_CREAT
user::rwx
group::rwx
other::
mask::rwx
group:31:rx
group:379:rx

